kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:latest
    commands:
      - npm install

  - name: test
    image: node:latest
    commands:
      - npm run test

  - name: deploy
    image: alpine
    commands:
      - "echo deploying"
    when:
      branch: ["main"]
      event: [push]
