kind: pipeline
type: docker
name: pre-deploy
trigger:
  branch: [main]
  event: [pull_request]

steps:
  - name: build
    image: node:latest
    commands:
      - npm install

  - name: test
    image: node:latest
    commands:
      - npm run test

---
kind: pipeline
type: docker
name: deploy
trigger:
  branch: [main]
  event: [push]

steps:
  - name: build image
    image: alpine
    commands:
      - "echo building image"
